### ISSUE TITLE
Notifications: Trying to get property 'view' of non-object in file

### ISSUE THREAD

**Issue by bpuig** [s-ichikawa/laravel-sendgrid-driver#108]
Hello, I'm trying to replace the forgot password reset link via notification and I'm getting this error:
`Trying to get property 'view' of non-object in file /var/www/***/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php on line 92`
**But the email is sent correctly** :confused:
```
#0 /var/www/****-api/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(92): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/var/www//****-...', 92, Array)
#1 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/Channels/MailChannel.php(63): Illuminate\Notifications\Channels\MailChannel->buildView(NULL)
#2 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(144): Illuminate\Notifications\Channels\MailChannel->send(Object(App\User), Object(App\Notifications\SendGridPasswordResetNotification))
#3 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(103): Illuminate\Notifications\NotificationSender->sendToNotifiable(Object(App\User), '662b5839-09e3-4...', Object(App\Notifications\SendGridPasswordResetNotification), 'mail')
#4 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Support/Traits/Localizable.php(19): Illuminate\Notifications\NotificationSender->Illuminate\Notifications\{closure}()
#5 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(105): Illuminate\Notifications\NotificationSender->withLocale(NULL, Object(Closure))
#6 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/NotificationSender.php(77): Illuminate\Notifications\NotificationSender->sendNow(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\SendGridPasswordResetNotification))
#7 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/ChannelManager.php(39): Illuminate\Notifications\NotificationSender->send(Object(Illuminate\Database\Eloquent\Collection), Object(App\Notifications\SendGridPasswordResetNotification))
#8 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Notifications/RoutesNotifications.php(18): Illuminate\Notifications\ChannelManager->send(Object(App\User), Object(App\Notifications\SendGridPasswordResetNotification))
#9 /var/www//****--api/app/User.php(55): App\User->notify(Object(App\Notifications\SendGridPasswordResetNotification))
#10 /var/www//****--api/vendor/laravel/framework/src/Illuminate/Auth/Passwords/PasswordBroker.php(62): App\User->sendPasswordResetNotification('c3e7caaff2d786c...')
```
SendGridPasswordResetNotification file:
```
<?php

namespace App\Notifications;

use Illuminate\Auth\Notifications\ResetPassword;
use Illuminate\Bus\Queueable;
use Illuminate\Mail\Message;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;
use Illuminate\Support\Facades\Lang;
use Mail;
use Sichikawa\LaravelSendgridDriver\Transport\SendgridTransport;

class SendGridPasswordResetNotification extends ResetPassword
{
    use Queueable;

    /**
     * The password reset token.
     *
     * @var string
     */
    public $token;

    /**
     * The callback that should be used to build the mail message.
     *
     * @var \Closure|null
     */
    public static $toMailCallback;

    /**
     * Create a notification instance.
     *
     * @param string $token
     * @return void
     */
    public function __construct($token)
    {
        parent::__construct($token);
    }

    /**
     * Get the notification's channels.
     *
     * @param mixed $notifiable
     * @return array|string
     */
    public function via($notifiable)
    {
        return ['mail'];
    }

    /**
     * Build the mail representation of the notification.
     *
     * @param mixed $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function toMail($notifiable)
    {
        if (static::$toMailCallback) {
            return call_user_func(static::$toMailCallback, $notifiable, $this->token);
        }

        \Mail::send([], [], function (Message $message) {
            $message
                ->from('no-reply@****.com')
                ->to('****@****.com')
                ->embedData([
                    'personalizations' => [
                        [
                            'dynamic_template_data' => [
                                'url' => env('APP_FRONTEND_URL') . '/reset-password/' . $this->token,
                                'expire' => config('auth.passwords.users.expire')
                            ],
                        ],
                    ],
                    'template_id' => '***',
                ], SendgridTransport::SMTP_API_NAME);
        });
    }

    /**
     * Set a callback that should be used when building the notification mail message.
     *
     * @param \Closure $callback
     * @return void
     */
    public static function toMailUsing($callback)
    {
        static::$toMailCallback = $callback;
    }
}

```
In User Model:
```
/**
     * Sends the password reset notification.
     *
     * @param string $token
     *
     * @return void
     */
    public function sendPasswordResetNotification($token)
    {
        $this->notify(new SendGridPasswordResetNotification($token));
    }
```

Any suggestions?

**Comment by bpuig** [comment]
🤦‍♂ I got the solution in Laravel docs:
https://laravel.com/docs/6.x/notifications#custom-channels

**Comment by juanhuerta** [comment]
> 🤦‍♂ I got the solution in Laravel docs:
> https://laravel.com/docs/6.x/notifications#custom-channels

So what was the solution?

**Comment by bpuig** [comment]
To be honest I don't remember and I ditched this library, now I'm using the official sendgrid php package. If it's supercrucial to you I can try to navigate back my repo and see what was done.

**Comment by juanhuerta** [comment]
That would be great @bpuig , I can't find any solution for this. Thanks!

**Comment by bpuig** [comment]
I don't know if it's this, but this is what I have found in my repo in some date I think I was using it. It's purpose was to send the reset password email. Hope it helps you in some way.

One file in App\Channels called SendGridChannel
```

<?php


namespace App\Channels;

use Illuminate\Notifications\Notification;

class SendGridChannel
{
    /**
     * Send the given notification.
     *
     * @param  mixed  $notifiable
     * @param  \Illuminate\Notifications\Notification  $notification
     * @return void
     */
    public function send($notifiable, Notification $notification)
    {
        $message = $notification->to($notifiable);
    }
}
```

And then a notification file:
```
<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Message;
use Illuminate\Notifications\Notification;
use Sichikawa\LaravelSendgridDriver\Transport\SendgridTransport;

class ApiMailResetPasswordNotification extends Notification
{
    use Queueable;

    public $token;

    /**
     * Create a new notification instance.
     *
     * @return void
     */
    public function __construct($token)
    {
        $this->token = $token;
    }

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return [SendGridChannel::class];
    }

    /**
     * Get the mail representation of the notification.
     *
     * @param  mixed  $notifiable
     * @return \Illuminate\Notifications\Messages\MailMessage
     */
    public function to($notifiable)
    {
        \Mail::send([], [], function (Message $message) use ($notifiable) {
            $message
                ->from('***@****')
                ->to($notifiable)
                ->embedData([
                    'personalizations' => [
                        [
                            'dynamic_template_data' => [
                                'token' => $this->token,
                            ],
                        ],
                    ],
                    'template_id' => '****',
                ], SendgridTransport::SMTP_API_NAME);
        });
    }
}

```

And then it was called like this:
 `(new ApiMailResetPasswordNotification($token))->to($user->email);`
