### ISSUE TITLE
Expected: object, given: array when ->from() is not specified

### ISSUE THREAD

**Issue by publicarray** [s-ichikawa/laravel-sendgrid-driver#96]
I got this error when attempting to send an email.

```
[2019-04-16 13:21:58] development.ERROR: Client error: `POST https://api.sendgrid.com/v3/mail/send` resulted in a `400 Bad Request` response:
{"errors":[{"message":"Invalid type. Expected: object, given: array.","field":"from","help":"http://sendgrid.com/docs/AP (truncated...)
 {"userId":1,"exception":"[object] (GuzzleHttp\\Exception\\ClientException(code: 400): Client error: `POST https://api.sendgrid.com/v3/mail/send` resulted in a `400 Bad Request` response:
{\"errors\":[{\"message\":\"Invalid type. Expected: object, given: array.\",\"field\":\"from\",\"help\":\"http://sendgrid.com/docs/AP (truncated...)
 at /Users/seb/git/attendize/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113)
[stacktrace]
#0 /Users/seb/git/attendize/vendor/guzzlehttp/guzzle/src/Middleware.php(66): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response))
#1 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))
#2 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\\Promise\\Promise::callHandler(1, Object(GuzzleHttp\\Psr7\\Response), Array)
#3 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\\Promise\\Promise::GuzzleHttp\\Promise\\{closure}()
#4 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(246): GuzzleHttp\\Promise\\TaskQueue->run(true)
#5 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(223): GuzzleHttp\\Promise\\Promise->invokeWaitFn()
#6 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(267): GuzzleHttp\\Promise\\Promise->waitIfPending()
#7 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(225): GuzzleHttp\\Promise\\Promise->invokeWaitList()
#8 /Users/seb/git/attendize/vendor/guzzlehttp/promises/src/Promise.php(62): GuzzleHttp\\Promise\\Promise->waitIfPending()
#9 /Users/seb/git/attendize/vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Promise\\Promise->wait()
#10 /Users/seb/git/attendize/vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('post', 'https://api.sen...', Array)
#11 /Users/seb/git/attendize/vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php(310): GuzzleHttp\\Client->__call('post', Array)
#12 /Users/seb/git/attendize/vendor/s-ichikawa/laravel-sendgrid-driver/src/Transport/SendgridTransport.php(76): Sichikawa\\LaravelSendgridDriver\\Transport\\SendgridTransport->post(Array)
#13 /Users/seb/git/attendize/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(71): Sichikawa\\LaravelSendgridDriver\\Transport\\SendgridTransport->send(Object(Swift_Message), Array)
#14 /Users/seb/git/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(484): Swift_Mailer->send(Object(Swift_Message), Array)
#15 /Users/seb/git/attendize/vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(259): Illuminate\\Mail\\Mailer->sendSwiftMessage(Object(Swift_Message))
#16 /Users/seb/git/attendize/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Mail\\Mailer->send('Emails.inviteUs...', Array, Object(Closure))
#17 /Users/seb/git/attendize/app/Http/Controllers/ManageAccountController.php(204): Illuminate\\Support\\Facades\\Facade::__callStatic('send', Array)
#18 [internal function]: App\\Http\\Controllers\\ManageAccountController->postInviteUser()
```

**Comment by publicarray** [comment]
Adding `->from('hello@example.com')`

Fixes the problem

Interesting since doing this was not required when connecting via smtp to sendgrid.

**Comment by publicarray** [comment]
Is there a way to add a default **from** address from an environment variable? thanks

**Comment by publicarray** [comment]
I tried using ` ->from(config('mail.from'))` but that does not work:

```
[2019-04-16 15:51:41] development.ERROR: Address in mailbox given [address] does not comply with RFC 2822, 3.6.2. {"userId":5,"exception":"[object] (Swift_RfcComplianceException(code: 0): Address in mailbox given [address] does not comply with RFC 2822, 3.6.2. at /Users/seb/git/attendize/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php:355)
```

**Comment by antonyakushin** [comment]
Based on the method signature you probably want to do:

```
->from(config('mail.from.address'), config('mail.from.name'))
```

At least in Laravel 5.8.

**Comment by publicarray** [comment]
Thanks, sorry I don't know what was wrong but everything is fine now.
